Hello microverse execise
rugwizangoga/Hello-Microverse pull request #1
Opened 2022-08-16 18:23 UTC by rugwizangoga

**Hello Microverse Project**

- Created A.hmtl file that has an h1 main title and a reference to its CSS file
- Created an A.css file that colors an h1 tag to my favorite color
- Added and configured linters to flag programming errors, bugs, stylistic errors, and suspicious constructs in our files

2022-08-16 18:36 UTC, omarsalem7 requested changes
Hi @rugwizangoga 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Good descriptive pull request ✔️
- No linter errors ✔️
- Good pull request title ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 18:36 UTC, omarsalem7 commented on README.md
> +Contributions, issues, and feature requests are welcome!
- [ ] Kindly add a link for issue page like this  `Feel free to check the [issues page](../../issues/).`

2022-08-16 18:36 UTC, omarsalem7 commented on README.md
> +Give a ⭐️ if you like this project!
- [ ] It will be better, if you add it licence like [this](https://github.com/microverseinc/readme-template#:~:text=License,is%20MIT%20licensed).

2022-08-17 07:09 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @rugwizangoga 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- No Linter errors ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
- Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

- [OPTIONAL] I suggest adding `Getting Started` section in your README.md file with some instructions about how to install and run the project 💯👌
> for example you can add
```
$ git clone git@github.com:rugwizangoga/Hello-Microverse.git
$ cd Hello-Microverse
```
Then open `index.html` on the bowser to run the project 👌

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 07:55 UTC, merged